### ISSUE TITLE
Excuse me,where is the code to train the model? 

### ISSUE THREAD

**Issue by mengzhangjian** [vsubhashini/caption-eval#2]
in https://vsubhashini.github.io/noc.html,The code to prepare data and train the model can be found in:  is empty

**Comment by vsubhashini** [comment]
Oh, will correct this over the weekend.

Thanks!

**Comment by mengzhangjian** [comment]
@vsubhashini  Thanks for your work!

**Comment by vsubhashini** [comment]
I have uploaded the models. Will make sure that things work before I post
the links.

On Oct 6, 2017 7:33 PM, "mengzhangjian" <notifications@github.com> wrote:

@vsubhashini <https://github.com/vsubhashini> Thanks for your work!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/vsubhashini/caption-eval/issues/2#issuecomment-334904897>,
or mute the thread

**Comment by mengzhangjian** [comment]
@vsubhashini   my pleasure, but  i can not find the model ,where ?

**Comment by vsubhashini** [comment]
Sorry about the delay. The code is here:
https://github.com/vsubhashini/noc/tree/recurrent/examples/noc 

It includes links to pre-trained models for generating captions and instructions for training. If you have questions please open an issue at that github repo. Thanks!
